### ISSUE TITLE
Documentation for Contributing

### ISSUE THREAD

**Issue by qwinters** [Clopen-Analysis/latex#1]
In order to have effective contributions, we probably want to have some firm policy guidelines for contributions. We want to make sure that there is high quality material of course!

Just thinking of a list of issues to address (not exhaustive) but these are some of the things I think it should cover: 

- [x] Types of contributions (sections? chapters? problem sets? worked examples?)
- [x] Length of a PR (should PRs be lengthy or should contributions be preferred in smaller chunks? do lengthy PRs require extra review criteria e.g. any PR over 2000 lines requires two admin approvals or something)
- [ ] Number of approvals needed for incoming PRs (how many people need to approve the PR? can they be anyone or do we want to have some sort of way of validating reviewers) 
- [x] Requirements for citations (what requires citations? theorems? proofs? examples?)
- [x] Originality requirements (I imagine that people copy pasting massive texts from a Textbook is a no-go even if it there is a citation) 
- [ ] Requirements for worked problems (are solved problems from textbooks allowed as contributions? if so are there requirements that should be put on allowing them to be linked back to the textbook? what about from past qualifying exams or just regular exams that professors have posted online?)
- [x] Prose guide: are there any requirements that should be put in place for prose? e.g. if you contribute a theorem, then you have to explain some amount of context around the theorem?
- [x] Uniqueness guide: how do we want to make sure that contributions are unique and we don't have lots of people working on the same issue? Should all contributions be required to come from a known cited issue? e.g. someone files an issue "Include Geometric Hahn-Banach separation theorem", then the issue gets prioritized, someone volunteers to take the issue and then they submit the PR, or should there just free range any PR goes
- [ ] LaTeX style guide: if we want to also integrate this into some sort of github publishing for a project website, we probably have to set up rules about what can be done in LaTeX e.g. MathJax won't render `\mathbbm{1}_A` for an indicator function (blackboard bold font style), so do we require all text be written with certain fonts?
- [ ] Notation guidelines: Probably we should aim to keep notation the same everywhere so I would imagine some notation guidelines would be important for contributors

**Comment by abackus** [comment]
I think it makes sense to put a contribution guide in the Preface of the document.

I think that the questions of pull requests and uniqueness can be deferred until the project scales up, if that ever happens.

**Requirements for citations**: I think a lot of proofs and examples in the field are fairly standard and don't need to be cited, though if a book was used as a reference it should be cited in the Preface at the very least. However, fairly specific examples should be cited, for example. Word-for-word plagiarism is banned.

**Requirements for worked problems**: I've been getting problems from old quals. tbh I have no idea how to cite such a thing, but I should probably figure that out.

**Prose guide**: All theorems should have some motivation, at least a sentence or two, and all prose should be in a subsec environment so it's numbered.

**Notation guidelines**: Good idea.
