### ISSUE TITLE
GitHub Actions/Bots to make life easier

### ISSUE THREAD

**Issue by qwinters** [Clopen-Analysis/latex#4]
A non-exhaustive list of suggestions for making contributions and working on the project smoother
- [x] [LaTeX linter](https://github.com/marketplace/actions/latex-linter-chktex) - run a linter on all .tex files to ensure good style
- [ ] Something along the lines of [paper-maker](https://github.com/marketplace/actions/paper-maker), [Build LaTeX on any Docker image](https://github.com/marketplace/actions/build-latex-on-any-docker-image) or something else to compile documents automatically (in a unified environment)
- [ ] [Pandoc Document Converter](https://github.com/marketplace/actions/pandoc-document-converter) (or its sequel because apparently it is "soft"-deprecated) to convert between different formats (e.g. Markdown for a Jekyll site)
- [x] [Changelogg](https://github.com/apps/changelogg) and [Semantic Pull Requests](https://github.com/settings/installations/11150643) for better version tracking (will help a lot if we have to correct errors from contributions that should not have been merged for example)
- [x] [todo](https://github.com/settings/installations/16071697) automatically create issues for comments with @todo in them (e.g. so PRs can be merged with non-blocking todos, but no one will forget about the todos) \
- [ ] [bulldozer](https://github.com/palantir/bulldozer) and [policy bot](https://github.com/palantir/policy-bot) so that PRs are always automatically merged when completed and proper approvals are met (helps prevent merge conflicts and merge conflicts => people improperly fixing them and thus careless mistakes)
- [x] [restyled](https://github.com/restyled-io/restyled.io) automatically fixes TeX code style issues (E.g. whitespacing issues)

**Comment by qwinters** [comment]
@abackus I don't think I have permissions to set up any of these, but more than happy to help you with setting them or I can do it if you set me up with privileges on the repo!

(Also not sure if all of them are necessary, but def think that policy bot + bulldozer; changelogg + semantic pull request; and todo would be extremely useful!)

**Comment by abackus** [comment]
I gave you ownership access, that should probably do the trick?

**Comment by qwinters** [comment]
I'll set them up later today!
