### ISSUE TITLE
Some random suggestions

### ISSUE THREAD

**Issue by v--** [Clopen-Analysis/latex#5]
I found out about this project via Reddit. It's a great start. I saw that you uploaded some code so I wanted to share some suggestions based on personal experience. I'm going to link my two public TeX repositories so that you can take a look at how I've set up my public projects. Of course, feel free to ignore whatever advice doesn't feel right to you.

* [LuaTeX](http://www.luatex.org/) may have been created with unicode and internationalization in mind, but even outside of that it seems to simply be the future of (La)TeX. It is specifically targeted by some features of lualatex-math or unicode-math or microtype, which improve a lot of miscellaneous stuff around TeX. Also, the ability to occasionally write lua code rather than TeX is great. Setting up LuaTeX is very straightforward in my experience. Both of the linked repositories use LuaLaTeX. See [this makefile](https://github.com/v--/notebook/blob/master/makefile) and [this makefile](https://github.com/v--/se2018/blob/master/makefile) for example. [Here](https://www.overleaf.com/learn/latex/Articles/The_TeX_family_tree:_LaTeX,_pdfTeX,_XeTeX,_LuaTeX_and_ConTeXt) is a disambiguation article about the different TeX engines.

* Having separate style files for different types of macros is also great for both maintainability and reusability. My repositories have a few macro files that could use some tidying up but I find it much nicer than keeping everything in the preamble. Speaking of macros, see [this file](https://github.com/v--/notebook/blob/master/packages/macros.sty) for my convention regarding naming. I think it is very predictable. In short,
  * I prefix blackboard bold letters with `\B` so that the natural numbers become `\BN`, the complex numbers become `\BC` and small `k` becomes `\Bk`.
  * Analogously, I prefix calligraphic letters with `\C`.
  * I have some notes about categories which use boldface by convention so rather than introducing different macros for every category I write `\Cat{Set}` or `\Cat{Vect}_{\Ck}`. I did similar things with probability distributions in another document - simply have `\D{Norm}` and `\D{Cauchy}` output a consistent style.
  * I like mathtools operators. The matrix rank of `A` becomes `\Rank{A}` and the closure of the set `S` in the weak* topology becomes `\Cl^{w^*}{S}`.
  * I like mathtools delimiters. See [this file](https://github.com/v--/notebook/blob/master/src/language_of_first_order_logic.tex#L346) for how I use them to put parentheses of varying size (there is a PDF linked in the repository where you can find the corresponding output near page 337).
  * I start my custom macros with a capital letter. It's not really a the brightest idea but I got used to it and I like it now. I'm not suggesting that you do it, I'm just explaining my all my macros start with a capital letter.
  * I prefix my labels similarly to the [fancyref](http://www.ctex.org/documents/packages/bibref/fancyref.pdf) convention - I prefix definitions with `def:`, I prefix theorems with `thm:`, etc. Whenever I have an equation in a theorem, e.g. `thm:banach_steinhaus`, I label the equation as `eq:thm:banach_steinhaus/condition` or something similar. I also have a lot of labels on list structures but I guess that granular degree of labeling is mostly useful for my own notes and not so much in a written book.

* Automated build: I see you have a PDF file in the repository but I also see you have created an issue about automated builds. You can see how I set up GitHub Actions for automated builds [here](https://github.com/v--/notebook/commit/31f9a206d0bc299984068680c988311f33763319). It recently stopped working so I migrated to a custom build server. Perhaps some alternative like [Travis CI](https://travis-ci.org/) is worth researching. 

* GitHub has a discussions feature. I think it is a great fit for similar repositories. Perhaps you should search for it in the project options and try to set it up.

**Comment by qwinters** [comment]
@v-- Do you mind breaking each of these major bullet points down into separate github issues? It will just help make sure conversations are focused and organized.

**Comment by v--** [comment]
@qwinters I'd maybe rather open a pull request for luaTeX and automated builds when I have the time. No place seems more appropriate for discussing those points than having the change in front of you.

Could you accept or reject the suggestion about  [GitHub Discussions](https://docs.github.com/en/discussions/quickstart#introduction). Feel free to close the issue after that.

**Comment by qwinters** [comment]
I think there's still an open question on if lualatex is the right move (vs. something that might be more amenable to web publishing via GitHub pages)

GitHub discussions is a great idea! I just don't think I have permissions to set that up. @abackus Might be able to/also give permissions?

**Comment by abackus** [comment]
> 
> 
> @qwinters I'd maybe rather open a pull request for luaTeX and automated builds when I have the time. No place seems more appropriate for discussing those points than having the change in front of you.
> 
> Could you accept or reject the suggestion about [GitHub Discussions](https://docs.github.com/en/discussions/quickstart#introduction). Feel free to close the issue after that.

Sure, I've enabled GitHub Discussions for the latex repo.

**Comment by v--** [comment]
Okay,
* I made a pull request about the automated builds - #10 .
* Maybe we should leave luatex out for now.
* I'm going to suggest the macro conventions in a discussion.
